name: Build and Deploy to Test Environment
on:
  workflow_dispatch:

jobs:
  build-and-deploy-to-test:
    runs-on: kaeser--product-navigator-dashboard--test--runner
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ gitea.event.inputs.ref || gitea.ref }}
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "npm"

      - name: Install packages
        run: |
          apt update
          apt install -y jq

      - name: Gather common variables
        id: gather-var
        run: |
          echo "GIT_HASH=$(git rev-parse --short=8 HEAD)" >> $GITHUB_ENV

      - name: Inject release into env file
        run: |
          RELEASE_VERSION_TAG=$(jq '.releaseVersion' package.json -r)
          sed -i "/^VITE_APP_VERSION/s/.*/VITE_APP_VERSION=\"$RELEASE_VERSION_TAG\"/" .env.testing
          cat .env.testing
          echo "RELEASE_VERSION_TAG=$RELEASE_VERSION_TAG" >> $GITHUB_ENV

      - name: Inject Google Cloud credentials
        run: echo "${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}" | base64 --decode > credentials.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:test

      - name: Prepare and publish npm package to Nexus
        run: |
          jq '.name = "pxpim-ui" | .version ="0.0.1-test-${{ env.RELEASE_VERSION_TAG }}"' package.json > package.json.tmp && mv package.json.tmp package.json
          npm config set registry https://cache.hz.pantopix.net/repository/npm-kaeser/
          npm config set email pantopix@pantopix.com
          npm config set //cache.hz.pantopix.net/repository/npm-kaeser/:_auth ${{ secrets.NEXUS_AUTH_BASE64 }}
          npm config set //cache.hz.pantopix.net/repository/npm-kaeser/:_authToken ${{ secrets.NPM_TOKEN }}
          npm publish

      - name: Install Cloud Foundry client
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          apt update
          apt install -y cf8-cli

      - name: Login to Cloud Foundry
        run: cf login -a ${{ secrets.CF_API }} -u ${{ secrets.CF_USER }} -p ${{ secrets.CF_PASSWORD }} -o kaeserq -s pantopix

      - name: Deploy to Cloud Foundry Test environment
        run: cf push --var CF_ENV=test

      - name: Set release version tag
        run: |
          apt update
          apt install -y yq jq
          echo "the release version is $RELEASE_VERSION_TAG"
          APP_NAME=$(yq '.applications[0].name' manifest.yml -r)
          REVISION_GUID=$(cf curl /v3/apps/$(cf app $APP_NAME --guid)/revisions/deployed | jq '.resources[0].guid' -r)
          cf curl -X PATCH v3/revisions/$REVISION_GUID -d "{ "metadata": { "labels": { "tag": "$RELEASE_VERSION_TAG" } }}"
          cf logout

      - name: Send email notification on failure
        if: ${{ failure() }}
        uses: https://github.com/joekrom/px-notifier@v0.0.3-alpha
        with:
          smtp_address: "smtp.office365.com"
          smtp_port: "587"
          username: ${{ secrets.NOTIFIER_EMAIL }}
          password: ${{ secrets.NOTIFIER_PASSWORD }}
          subject: ${{ github.workflow }}
          ssl: "true"
          from: ${{ secrets.NOTIFIER_EMAIL }}
          to: ${{ github.event.pusher.email }}, bogdan.rad@pantopix.com, joel.fankam@pantopix.com, andrei.milas@pantopix.com
          body: "build and deployment failed with ref: ${{ github.ref_name }}, link : ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_number }}"

      - name: Send email notification to teams channel on failure
        if: ${{ failure() }}
        run: |
          git clone --branch main https://${{ secrets.DEPLOY_TOKEN }}@git.pantopix.net/PANTOPIX/templates.git
          sed -i -e "s/activity_title_t/${{ github.workflow }}/g" \
            -e "s/activity_subtitle_t/px-notifier/g" \
            -e "s/date_t/$(date)/g" \
            -e "s/assigned_to_t/${{ github.event.head_commit.committer.name }}/g" \
            -e "s/status_t/failed/g" \
            -e "s@message_t@pipeline failed with ref: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_number }}@g" \
            -e "s@link_to_commit_t@${{ github.event.head_commit.url }}@g" \
            -e "s/commit_hash_t/${{ env.GIT_HASH }}/g" \
            templates/teams-card/card.json
          curl -H "Content-Type: application/json" -d "$(cat templates/teams-card/card.json)" "https://axxeptade.webhook.office.com/webhookb2/b58cccd4-ae0c-4969-8722-9650ab34f9d0@bc2cff9d-590d-4563-b1af-ded8a3badb14/IncomingWebhook/ab62548bfca54444a82998c44338b45d/24e202af-1164-4a71-ae74-b32dfb409137" -v --trace-ascii trace.txt
