name: Mirroring (main, rc, release, hotfix branches)
on:
  push:
    branches: ["main", "rc/**", "release/**", "hotfix/**"]

jobs:
  sync:
    runs-on: kaeser--product-navigator-dashboard--test--runner
    steps:
      - name: Set environment variables
        run: |
          CLONE_URL=${{ gitea.event.repository.clone_url }}
          HOSTNAME=$(echo "$CLONE_URL" | awk -F 'https://' '{print $2}')
          TARGET_DIR=$(echo "$HOSTNAME" | awk -F '/' '{print $NF}')

          echo "CLONE_URL=$CLONE_URL" >> $GITHUB_ENV
          echo "HOSTNAME=$HOSTNAME" >> $GITHUB_ENV
          echo "TARGET_DIR=$TARGET_DIR" >> $GITHUB_ENV
          echo "DEPLOY_TOKEN=${{ secrets.DEPLOY_TOKEN }}" >> $GITHUB_ENV
          echo "KEINI0008_NAVIGATOR_DASHBOARD_MIRROR_TOKEN=${{ secrets.KEINI0008_NAVIGATOR_DASHBOARD_MIRROR_TOKEN }}" >> $GITHUB_ENV
          echo "KEINI0008_NAVIGATOR_DASHBOARD_MIRROR_USER=${{ secrets.KEINI0008_NAVIGATOR_DASHBOARD_MIRROR_USER }}" >> $GITHUB_ENV

      - name: Display parameters
        run: |
          echo "CLONE_URL: $CLONE_URL"
          echo "HOSTNAME: $HOSTNAME"
          echo "TARGET_DIR: $TARGET_DIR"
          echo "MIRROR_USER: $KEINI0008_NAVIGATOR_DASHBOARD_MIRROR_USER"

      - name: Mirror repository
        if: ${{ success() }}
        run: |
          git clone --mirror --single-branch -b main https://deploy:${DEPLOY_TOKEN}@${HOSTNAME}
          cd $TARGET_DIR && git config --global KEINI0008_NAVIGATOR_DASHBOARD_MIRROR_USER && git config --global user.password $KEINI0008_NAVIGATOR_DASHBOARD_MIRROR_TOKEN
          git fetch origin main:refs/remotes/origin/main 'refs/heads/rc/*:refs/remotes/origin/rc/*' 'refs/heads/rc/*:refs/remotes/origin/release/*' 'refs/heads/hotfix/*:refs/remotes/origin/hotfix/*'
          git remote set-url --push origin https://x-token-auth:${KEINI0008_NAVIGATOR_DASHBOARD_MIRROR_TOKEN}@bitbucket.org/prod-kaeser/keini0008-navigator-dashboard.git
          git push --mirror
